### ISSUE TITLE
Missing image reader

### ISSUE THREAD

**Issue by fmarisa** [jai-imageio/jai-imageio-core#29]
Hi,

Trying to load the plugin JPEG2000 the JPEG2000 reader is not loaded and it later results in an exception : 

 org.apache.pdfbox.filter.MissingImageReaderException: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
	at org.apache.pdfbox.filter.Filter.findImageReader(Filter.java:128)
	at org.apache.pdfbox.filter.JPXFilter.readJPX(JPXFilter.java:72)
	at org.apache.pdfbox.filter.JPXFilter.decode(JPXFilter.java:56)
	at org.apache.pdfbox.cos.COSInputStream.create(COSInputStream.java:69)

The issue seems to be that the ServiceRegistry class does not contain the jpeg class, simply because it is not in the classpath. Why is it not in the classpath? Well we're not certain. It is present in the jar we're launching but not in the classpath.

However if we add the jar jpeg2000 to the classpath before our jar-with-dependencies then it does get loaded... eg this works

 java -cp jai-imageio-jpeg2000-1.3.0.jar:my-jar-with-dependencies.jar ...

this does not work
 
 java -cp my-jar-with-dependencies.jar ... 

Even though my-jar-with-dependencies.jar contains the  classes in jai-imageio-jpeg2000-1.3.0.jar

**Comment by lobsangludd** [comment]
Plugins are loaded via META-INF/services/javax.imageio.spi.ImageReaderSpi - [DOCS](https://docs.oracle.com/javase/7/docs/api/javax/imageio/spi/IIORegistry.html)

Since you're putting multiple plugins in the same jar, this file is overwritten. You'll have to register them manually:

```
IIORegistry registry = IIORegistry.getDefaultInstance();
registry.registerServiceProvider(new com.github.jaiimageio.jpeg2000.impl.J2KImageReaderSpi()); 
```

**Comment by JamzTheMan** [comment]
OMG thank you! I had a similiar issue dealing after adding TwelveMonkeys PSD/ImageIO plugins and this solved the issue when building the app in an uber-jar!

Thought this deserved a shot out as it took an hour of Google-foo to get here lol

**Comment by michi88** [comment]
If you're using the maven shade plugin you can also use the following transformer:

```xml
<transformers>
    <!-- needed for jpeg2000 services to be included properly -->
    <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
</transformers>
```

**Comment by shrutibidada** [comment]
> Plugins are loaded via META-INF/services/javax.imageio.spi.ImageReaderSpi - [DOCS](https://docs.oracle.com/javase/7/docs/api/javax/imageio/spi/IIORegistry.html)
> 
> Since you're putting multiple plugins in the same jar, this file is overwritten. You'll have to register them manually:
> 
> ```
> IIORegistry registry = IIORegistry.getDefaultInstance();
> registry.registerServiceProvider(new com.github.jaiimageio.jpeg2000.impl.J2KImageReaderSpi()); 
> ```

This worked for me
